version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
  web:
    build: .
    command: bash -c "yarn install --check-files && rm -f tmp/pids/server.pid && bundle exec rails s -p 3005 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3005:3005"
    depends_on:
      - db